name: ecodrive
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  syncfusion_flutter_gauges: ^27.1.48
  firebase_core: ^3.6.0
  firebase_database: ^11.1.3
  firebase_storage: ^12.3.0
  mqtt_client: ^10.5.1
  google_fonts: ^6.1.0
  provider: ^6.1.1
  flutter_local_notifications: ^17.2.2
  http: ^1.2.2
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - ML/models/driver_model.tflite
    - ML/models/vehicle_model.tflite
    - ML/models/driver_classes.txt
    - ML/models/vehicle_classes.txt
    - ML/models/driver_preprocess.json
    - ML/models/vehicle_preprocess.json

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/app_icon.png"
  adaptive_icon_background: "#00000000"   # transparent background
  adaptive_icon_foreground: "lib/assets/logo.png"

