// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzgm29LwAjRBJc0NDsUvtWw2ghgRMLe-k',
    appId: '1:124541748622:web:c9c26d6edcc363743e50df',
    messagingSenderId: '124541748622',
    projectId: 'ecodrive-85155',
    authDomain: 'ecodrive-85155.firebaseapp.com',
    databaseURL: 'https://ecodrive-85155-default-rtdb.firebaseio.com',
    storageBucket: 'ecodrive-85155.firebasestorage.app',
    measurementId: 'G-97ZT308PJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjlXZlC8fQiNmSLMzmQF-m5PjUxkxLWlc',
    appId: '1:124541748622:android:4a2e68f193c3e87d3e50df',
    messagingSenderId: '124541748622',
    projectId: 'ecodrive-85155',
    databaseURL: 'https://ecodrive-85155-default-rtdb.firebaseio.com',
    storageBucket: 'ecodrive-85155.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWt-_GUIPaudkX37RJJcJ4BcaXagcMLlY',
    appId: '1:124541748622:ios:d52eb0508201dd5b3e50df',
    messagingSenderId: '124541748622',
    projectId: 'ecodrive-85155',
    databaseURL: 'https://ecodrive-85155-default-rtdb.firebaseio.com',
    storageBucket: 'ecodrive-85155.firebasestorage.app',
    iosClientId: '124541748622-hh7udrisnk9gjd20te6eifjhk8vobegc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollutionapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWt-_GUIPaudkX37RJJcJ4BcaXagcMLlY',
    appId: '1:124541748622:ios:d52eb0508201dd5b3e50df',
    messagingSenderId: '124541748622',
    projectId: 'ecodrive-85155',
    databaseURL: 'https://ecodrive-85155-default-rtdb.firebaseio.com',
    storageBucket: 'ecodrive-85155.firebasestorage.app',
    iosClientId: '124541748622-hh7udrisnk9gjd20te6eifjhk8vobegc.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollutionapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzgm29LwAjRBJc0NDsUvtWw2ghgRMLe-k',
    appId: '1:124541748622:web:c8ea57f648266fbf3e50df',
    messagingSenderId: '124541748622',
    projectId: 'ecodrive-85155',
    authDomain: 'ecodrive-85155.firebaseapp.com',
    databaseURL: 'https://ecodrive-85155-default-rtdb.firebaseio.com',
    storageBucket: 'ecodrive-85155.firebasestorage.app',
    measurementId: 'G-92D3LHZ9FH',
  );

}